# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle Unit Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  #verification:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew test
      
    - name: Send mail
      # if: success() / failure() で成否次第で動かしたり動かさなかったり出来る
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        # SMTPサーバ・ポート
        server_address: smtp.alpha-prm.jp
        server_port: 465
        # 送信元アカウント（設定値は Settings の Sercrets でKey-Value指定で設定）
        username: ${{secrets.ALPHA_MAIL_ADDRESS}}
        password: ${{secrets.ALPHA_MAIL_ADDRESS_PASSWORD}}
        # 件名
        subject: ${{github.job}} job of ${{github.repository}} has ${{job.status}}. actor is ${{github.actor}}
        # 本文
        body: |
          github.action_path      : ${{ github.action_path }}
          github.actor            : ${{ github.actor }}
          github.base_ref         : ${{ github.base_ref }}
          github.event            : ${{ github.event }}
          github.event_name       : ${{ github.event_name }}
          github.event_path       : ${{ github.event_path }}
          github.head_ref         : ${{ github.head_ref }}
          github.job              : ${{ github.job }}
          github.ref              : ${{ github.ref }}
          github.repository       : ${{ github.repository }}
          github.repository_owner : ${{ github.repository_owner }}
          github.run_id           : ${{ github.run_id }}
          github.run_number       : ${{ github.run_number }}
          github.sha              : ${{ github.sha }}
          github.token            : ${{ github.token }}
          github.workflow         : ${{ github.workflow }}
          github.workspace        : ${{ github.workspace }}
          
          job.container           : ${{ job.container }}
          job.container.id        : ${{ job.container.id }}
          job.container.network   : ${{ job.container.network }}
          job.status              : ${{ job.status }}
          
          runner.os               : ${{ runner.os }}
          runner.temp             : ${{ runner.temp }}
          runner.tool_cache       : ${{ runner.tool_cache }}
        # 送信先. 送信先が複数の場合は , で区切る。 cc, bcc も指定可能
        to: ${{secrets.TO_MAIL_ADDRESS}}
        from: XYZ
        # TLS (default is true if server_port is 465)
        secure: true
