# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle Unit Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  #verification:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew test
      
    - name: Send mail
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        # Server & Port:
        server_address: smtp.gmail.com
        server_port: 465
        # user credentials
        username: ${{secrets.MAIL_ADDRESS}}
        password: ${{secrets.MAIL_ADDRESS_PASSWORD}}
        # email subject
        subject: Title.
        # email body as text
        body: Message.
        # comma-separated string, send email to
        #to: abc@gmail.com,xyz@gmail.com
        to: ${{secrets.TO_MAIL_ADDRESS}}
        # from email name
        from: XYZ
        secure: true
